name: CI/CD

on:
  push:
    branches:
      - master
    tags:
      - "*"
    paths:
      - ".github/workflows/ci.yml"
      - "**.py"
      - "pdm.lock"
      - "!baize/__version__.py"
  pull_request:
    branches:
      - master
    paths:
      - ".github/workflows/ci.yml"
      - "**.py"
      - "pdm.lock"
      - "!baize/__version__.py"

jobs:
  tests:
    name: "Python ${{ matrix.python-version }} ${{ matrix.os }}"
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/cache@v2.1.6
        id: cache-requirements
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ matrix.python-version }}-${{ hashFiles('pdm.lock', 'pyproject.toml') }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip pdm
          pdm install -dG dev --no-self
      - name: Static type and format checking
        run: |
          python script/check.py
      - name: Generate coverage report
        run: |
          pytest --cov=./baize --cov-report=xml -o log_cli=true -o log_cli_level=DEBUG
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          files: ./coverage.xml
          directory: ./coverage/reports/
          verbose: true

      - name: Install extras
        run: |
          pdm install -G multipart --no-self
      - name: Tests
        run: |
          pytest --cov=./baize --cov-report=xml -o log_cli=true -o log_cli_level=DEBUG
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          files: ./coverage.xml
          directory: ./coverage/reports/
          verbose: true

      - name: Install with mypyc
        run: |
          pdm install
      - name: Tests built by mypyc
        run: |
          pytest -o log_cli=true -o log_cli_level=DEBUG
      - name: Test without mypy-extensions
        run: |
          pip uninstall -y mypy-extensions
          pytest -o log_cli=true -o log_cli_level=DEBUG

  publish:
    needs: tests
    if: startsWith(github.ref, 'refs/tags/')

    name: "Python ${{ matrix.python-version }} ${{ matrix.os }}"
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v1

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip==21.1.3 pdm wheel twine
          pdm install -dG build

      - name: Build
        run: |
          pdm build

          pdm export -f setuppy -o setup.py
          pip uninstall -y mypy
          python setup.py bdist_wheel

      - name: Publish
        run: |
          twine upload --username AberSheeran --password ${{ secrets.PYPIPASS }} --verbose --skip-existing dist/*
